travis:
  secure:
    BINSTAR_TOKEN: EHf1HV61lHBxmJ7QMf3Ok28WsWuTrzxM06EwDD2tpFbME1niU0aNOQUCel8Xl2lD3bIAK+bnQ/9W5AHwgEq9Jzj8zur3KKOkU4tg0kvdpd096lI7IXbLluxrjbOjVUtvTWPgkAVaDMnick4F6xSGsgBJ6knCLHH33VToNUoOW+v5qLadzPAysE3ezElGMzbJ2jypi18QfEKDK63SanpeO8OpOQfv/AlHyRq4kA9kx7pCtz0abwpjyywSichgGNqUUd9CGMJN/zG2cE8dvyLn0nIQr/6MNM/SXQDY7QsTFLIvpQ7hVXIq1OidbwVKmLE74a7+lLF2BeagLWmWnpnfn6nxv0wDy/eWWfQndYfg7Er1OjJRr1e0rlNBdjBdkXTzo9r9DnZnao6VmhH3JoHdy7c9UeaqWXzWCZLmcd2cT1j8+nwMoOkeJDm0UYi7XZJ7W+vLHRT3E9DDGK4l2FhkA71t0m9e/dQHKlXVPkajQlbawPrONW7/W7yr3m2w6AWG2rUt8BD9y0T1CqdxTPi4aKWmVD2pUHF6Za9a6DfjQVB7BGV6ui0GwYZUffamP8lGJ4A+hZAFol+9CZejJuvZz86Ji4BQCap5OUh3uquLkWnX6ievQ1cIruLwBK0bdDvQDHuAhs0FnWcuzvt/L+6xkZvMcrA3WdI44THDZPuusLU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
